#if ANDROID
using Com.Bnotech.ExtendedWebView.Platforms.Android.Handlers;
#elif IOS
using Com.Bnotech.ExtendedWebView.Platforms.iOS.Handlers;
#endif

namespace Com.Bnotech.ExtendedWebView;

public static class AppBuilderExtensions
{
    /// <summary>
    /// Setup the Extended WebView
    /// </summary>
    /// <param name="builder"><see cref="MauiAppBuilder"/> generated by <see cref="MauiApp"/> </param>
    /// <returns><see cref="MauiAppBuilder"/> initialized for <see cref="IExtWebView"/></returns>
    public static MauiAppBuilder UseExtendedWebView(this MauiAppBuilder builder)
    {
        builder
            .ConfigureMauiHandlers((handlers) =>
            {
#if ANDROID
                handlers.AddHandler(typeof(ExtWebView), typeof(ExtWebViewHandler));
#elif IOS
                handlers.AddHandler(typeof(ExtWebView), typeof(ExtWebViewHandler));
#endif
            });

        return builder;
    }
}

