name: Build .NET Libraries

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./ExtendedWebView

jobs:
  build:
    runs-on: windows-latest
    env:
      working-directory: ./ExtendedWebView
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x
        
      - name: Install MAUI workload
        run: dotnet workload install maui
      
      - name: Add Nuget Package Repository
        run: |
          dotnet nuget add source --username bnoffer --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/bnotech/index.json"
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build