name: Publish .NET Libraries Preview

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-pre[0-9][0-9][0-9]"

defaults:
  run:
    working-directory: ./ExtendedWebView

jobs:
  build:
    runs-on: windows-latest
    env:
      working-directory: ./ExtendedWebView
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Verify commit exists in origin/main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main
      
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Add Nuget Package Repository
        run: |
          dotnet nuget add source --username bnoffer --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/bnotech/index.json"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build ExtendedWebView.csproj -c Release --no-restore
      
      - name: Pack
        run: |
          $version=${{ steps.tag.outputs.result }}
          $version=$version.replace("refs/tags/v", "")
          dotnet pack --configuration Release --verbosity detailed --output ../package -p:PackageVersion=$version 
      - name: Push
        run: |
          $version=${{ steps.tag.outputs.result }}
          $version=$version.replace("refs/tags/v", "")
          $package="../package/ExtendedWebView." + $version + ".nupkg"
          dotnet nuget push $package --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"